### PR TITLE
Issue 38 add statistics

### PR DESCRIPTION
**Pull request by jneubert**
As a first take on #38 , here a script which creates class and property statistics from LOD4ALL and Openlink LOD stores, and the according statistics.

### CODE REVIEW

**Comment by osma** [comment]
It would be interesting to get some statistics also about the property value types, for example URI vs. blank node vs. literal. Do you think the queries could be easily adapted to do that @jneubert ? For example just adding a `FILTER(isIRI(?value))` or similar could narrow down the number of results. I think this kind of stats would be very useful for the discussion about property ranges (#32, #36).

**Comment by jneubert** [comment]
@osma Great suggestion! The query should not be the problem. However, do you have an idea on how to present the results?
Perhaps we should use only the most complete and recent store, and have separate tables with 4 columns (total, % IRI, % literal, % blank)?

**Comment by osma** [comment]
That sounds reasonable. I was also picturing a table with those columns (either percentages or absolute counts, whichever is easiest to compute). Not sure which store would be best for this purpose, but I would at least like to try this out on LOD-a-lot.

**Comment by jneubert** [comment]
OK, I'm trying to hack something, using Openlink as test env.

**Comment by osma** [comment]
@jneubert Out of curiosity - why are you using VALUES blocks in the queries? Since AFAICT there is only ever one value (URI) per query, this seems redundant. You could use BIND or even just put the VALUE placeholder within the query body itself (e.g. in the class query, use `?s a VALUE` which gets substituted into e.g. `?s a <http://purl.org/dc/terms/Agent>`)

In my experience, at least Fuseki has trouble optimizing queries using VALUES and you will likely get faster results if you can avoid using it.

I got the LOD-a-lot endpoint up, currently running the get_statistics.pl script against it.

**Comment by osma** [comment]
Another thought: Including LOV is a great idea, but I suspect the current queries may not be making the best use of it. For example `subClassOf` and `subPropertyOf` statements in LOV would not be counted, since the class query only counts `rdf:type` triples and the property query only counts triples where the property is actually used as a property, not when it is an object of `subPropertyOf`.

**Comment by jneubert** [comment]
I haven't seen recognizable performance differences between VALUES, BIND, and direct substitution. But if this is an issue (perhaps particularly in fuseki/hdt), I'm happy to replace that. Otherwise I'd slightly tend to keep a named variable.

**Comment by osma** [comment]
BIND vs direct substitution is not a big issue, it seems to run fine this way.

**Comment by jneubert** [comment]
@osma Thank you very much for your suggestions and your work with the script. I suppose we should re-think its metadata and control flow structure. Adding the value types report was quite a hack (though very useful), and my feeling is that adding a separate query for subProperty/subClass relationships for LOV and/or a query to a local endpoint - which may not be available on another site - could overstretch the current structure.
BTW, I'm amazed how fast you had the LOD-a-lot endpoint up and running. Did you use https://github.com/rdfhdt/hdt-java/tree/master/hdt-fuseki for that?

**Comment by osma** [comment]
@jneubert Thanks to you for writing the script and the queries! Thanks to that I was able to concentrate on setting up LOD-a-lot, which I admit went surprisingly quickly. I used hdt-fuseki as you guessed, but I had to use the `long-dict-id` branch of `hdt-java` because of the size of the data set. Luckily I was aware of this before I started so I didn't have any big issues. Most of the time was for getting enough disk space allocated to the big server I have available (luckily the IT people responded very quickly!), and for downloading the 500+GB LOD-a-lot data, which took around 3 hours.

Yes, we could perhaps re-think the architecture of the script. I think these queries could be interesting:

1. Class usage (`rdf:type`) statistics, as we have currently
2. Property usage statistics broken down by literal vs IRI (blank node values can be ignored, since they seem to be extremely few)
3. References to classes as object (e.g. `owl:subClassOf`)
4. References to properties as object (e.g. `owl:subPropertyOf`)

The query types 1 and 2 are most interesting for the big aggregate data sets, but could be run on LOV as well (to capture usage of DCTerms in ontology definitions), while query types 3 and 4 are mainly for LOV but could be run on the big ones too. For all these cases I would try to simplify the queries to their bare minimum (including avoiding BIND and VALUES) to make the queries as lightweight as possible for the endpoints.

I'm not very convinced the idea of using federation to query both LOD-a-lot and Openlink would work, since it would involve transferring potentially huge (tens of millions of rows or more) result sets between the endpoints. But it might work, at least for classes/properties with lower usage counts. I could test this separately, it doesn't have to be in the main script.

I'm a bit rusty on Perl (stopped using it ~20 years ago!) so my preference would be to rewrite the script in Python 3 using SPARQLWrapper for accessing endpoints.

**Comment by jneubert** [comment]
@osma Just a quick remark on federation: I have good experiences even with larger datasets - e.g., fetching all GND IDs from Wikidata and aggregating them by GND class within a GND endpoint ([query](https://api.github.com/repos/zbw/sparql-queries/contents/gnd/count_wd_by_gnd_class.rq), [result](https://www.wikidata.org/wiki/Property_talk:P227#GND_ID_count_by_GND_Ontology_class)). It was half a million instead of tens of millions there, but it _may_ work unless you hit a timeout on the remote service.

**Comment by jneubert** [comment]
@osma I agree with the list of relevant queries/reports in https://github.com/dcmi/usage/pull/40#issuecomment-400578810. I'm not sure if avoiding a bind makes a difference for the endpoints, but on the other hand, we can comment about the queries in the code of the script, so there is no need for them to be self-documenting. 

Unfortunatly, I'm illiterate re. Python, and this script isn't an appealing-enough case to learn it. So, we could go on with Perl (me coding, and integrating comments by you and others), or you could take over development with a rewrite in Python, with comments/suggestions by me. I'm fine with both options.

What we should do anyway is extending the script in order to work on DC Elements or any other of the [DC-defined the classes and properties](https://github.com/dcmi/purls/blob/master/purls-handled-automatically-by-partial-redirects.txt).

**Pull request merged**
